USB_VID = 0x239A
USB_PID = 0x8070
USB_PRODUCT = "Bluebird"
USB_MANUFACTURER = "Teknikio"

MCU_CHIP = nrf52840
SOFTDEV_VERSION = 7.0.1

INTERNAL_FLASH_FILESYSTEM = 1
MICROPY_PY_ASYNC_AWAIT = 0
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_AUDIOCORE = 1
CIRCUITPY_AUDIOPWMIO = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_TIME = 1

CIRCUITPY_BUSIO_SPI = 0
CIRCUITPY_COMPUTED_GOTO_SAVE_SPACE = 1
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AESIO = 0